### ISSUE TITLE
JS error

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.newsticker#27]
With Plone 5.0.4 after activating the add-on I had a JS error. To allow the site and news ticker to function correctly I had to enable JS dev mode in the configuration registry.

![newstickerjserror](https://cloud.githubusercontent.com/assets/815418/24166110/441f024a-0e40-11e7-8be9-e2918d69934b.png)

**Comment by hvelarde** [comment]
are you using 2.0? we tested against Plone 5.1 and it was working fine.

**Comment by hvelarde** [comment]
just tested on a brand new Plone 5.0.7 and is working:

![selection_023](https://cloud.githubusercontent.com/assets/341393/24171423/2dfcb34a-0e63-11e7-8c3e-022f808eb1ea.png)

**Comment by tkimnguyen** [comment]
it was 2.0b1 from pypi

**Comment by tkimnguyen** [comment]
Yes, 2.1b1 works fine with 5.0.7. Sorry!
