### ISSUE TITLE
news ticker does not appear on add-on activation

### ISSUE THREAD

**Issue by tkimnguyen** [collective/collective.newsticker#31]
... you have to visit @@newsticker-settings and press Save button before the news ticker actually appears.

2.1b1 and Plone 5.0.7

**Comment by hvelarde** [comment]
yes, that the expected behavior because you have to select a collection as the source of your ticker; it's documented on the README.

**Comment by tkimnguyen** [comment]
Wouldn't /news be a good default?

**Comment by hvelarde** [comment]
no, because not all sites have a `/news` collection alive.
